# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set working dir to root of repo
Dir.chdir ".."

VAGRANTFILE_API_VERSION = "2" # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Settings for all vms
  if Vagrant.has_plugin?("vagrant-cachier")     
    config.cache.scope = :box   
  end

  # Handle local proxy settings
  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
    end
  end

  
  config.vm.define "devstack" do |ds|
    ds.vm.hostname = "devstack"
    ds.vm.box = "ubuntu/trusty64"
    ds.vm.network :private_network, ip: "192.168.10.5"
    ds.vm.provider "virtualbox" do |vb|
      vb.memory = 7180
      vb.cpus = 4
    end
    ds.vm.provision "ansible" do |ansible|
      ansible.playbook = "ds-build.yml"
      ansible.raw_arguments = ['-T 30', '-e pipelining=True']
    end
  end

end
