- hosts: devstack
  sudo: yes
  vars:
    monasca_api_host: 192.168.10.4
    monasca_agent:
      user: monasca-agent
      password: password
      project: mini-mon
    minimon:
      user: mini-mon
      password: password
    monasca_api_url: http://{{ monasca_api_host }}:8080/v2.0
    monasca_checks:
      host_alive:
        init_config:
          ssh_port: 22
          ssh_timeout: 0.5
          ping_timeout: 1
        instances:
          - name: mini-mon
            host_name: 192.168.10.4
            alive_test: ssh
    keystone_url: http://192.168.10.5:35357/v3
    keystone_admin_token: ADMIN
    keystone_users:
      mini-mon:
        project: mini-mon
        password: password
        role: monasca-user
      monasca-agent:
        password: password
        project: mini-mon
        role: monasca-agent
  tasks:
    - name: Setup the monasca cli credentials in the default environment
      copy: src=tests/env.sh dest=/etc/profile.d/monasca_cli.sh owner=root group=root mode=0644
      tags:
        - cli
  roles:
    - {role: monasca-ui, tags: [ui]}
    - {role: monasca-keystone, tags: [devstack, keystone]}
    - {role: monasca-devstack, tags: [devstack]}
    - {role: monasca-agent, tags: [agent]}

