- hosts: devstack
  sudo: yes
  vars:
    monasca_checks:
      host_alive:
        init_config:
          ssh_port: 22
          ssh_timeout: 0.5
          ping_timeout: 1
        instances:
          - name: mini-mon
            host_name: 192.168.10.4
            alive_test: ssh
  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes
      ignore_errors: true
    - name: Install virtualenv
      apt: name=python-virtualenv
  tasks:
    - name: Setup the monasca cli credentials in the default environment
      copy: src=tests/env.sh dest=/etc/profile.d/monasca_cli.sh owner=root group=root mode=0644
      tags:
        - cli
    - name: Update cli
      pip: name=python-monascaclient state=latest virtualenv="{{monasca_virtualenv_dir}}"
      tags:
        - cli
  roles:
    - {role: monasca-ui, tags: [ui]}
    - {role: monasca-keystone, tags: [devstack, keystone]}
    - {role: monasca-devstack, tags: [devstack]}
    - {role: monasca-agent, tags: [agent]}
