- hosts: mini-mon
  sudo: yes
  vars:
    mini_mon_host: 192.168.10.4
    influxdb:
      version: 0.8.1
      raft_port: 9090
      seed_servers: []
      replication_factor: 1
    kafka_hosts: "{{mini_mon_host}}:9092"
    zookeeper_hosts: "{{mini_mon_host}}:2181"
  roles:
    - {role: tkuhlman.kafka, kafka_listen_address: "{{mini_mon_host}}", tags: [kafka]}
    - {role: stympy.influxdb, tags: [influxdb]}
    - {role: tkuhlman.percona, mysql_root_password: password, percona_package: percona-xtradb-cluster-56, tags: [mysql, percona]}
    - {role: tkuhlman.monasca-persister,
       kafka_uri: "{{kafka_hosts}}",
       influxdb_host: "{{mini_mon_host}}",
       influxdb_user: mon_persister,
       influxdb_password: password,
       tags: [influxdb]}
    - {role: tkuhlman.monasca-notification,
       mysql_host: "{{mini_mon_host}}",
       mysql_user: notification,
       mysql_password: password,
       smtp_host: localhost,
       tags: [notification]}
  tasks:
    - name: Install postfix, needed by notification engine
      apt: name=postfix state=present
