- hosts: mini-mon
  tasks:
    - name: Populate vars
      template: src=tests/smoke2.py.j2 dest=/vagrant/tests/smoke2.py mode=0775
    - name: Copy config
      copy: src=tests/smoke2_configs.py dest=/vagrant/tests/smoke2_configs.py
    - name: Run the smoke2 test
      command:  /vagrant/tests/smoke2.py
      environment:
        PATH: "{{ansible_env.PATH}}:{{monasca_virtualenv_dir}}/bin"
      register: smoke2
    - debug: var=smoke2.stdout_lines