# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2" # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Settings for all vms
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../Berksfile"

  config.vm.box = "hlinux"
  config.vm.guest = :debian   # bypass vagrant guest type autodetection
  # hlinux is not currently working with virtual box shared folders so minimize shared folders and switch to rsync
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.hostname = 'mini-mon'
  config.vm.network :private_network, ip: "192.168.10.4"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 4
  end

  config.vm.provision :chef_solo do |chef|
    chef.synced_folder_type = "rsync"
    chef.roles_path = "../roles"
    chef.data_bags_path = "../data_bags"
    chef.add_role "Mini-Mon"
  end

end
