# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2" # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Settings for all vms
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../Berksfile"

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'hp'
  config.vm.box = "dummy_hp"
  config.vm.box_url = "https://github.com/mohitsethi/vagrant-hp/raw/master/dummy_hp.box"
  config.vm.hostname = 'mini-mon'
  config.vm.synced_folder "..", "/vagrant"  # needed to get vertica packages but otherwise unneeded

  config.vm.provision :shell, path: "./chef-solo-bootstrap.sh"

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "../roles"
    chef.data_bags_path = "../data_bags"
    chef.add_role "Mini-Mon"
  end
end
